### ISSUE TITLE
issue with x-axis width

### ISSUE THREAD

**Issue by darkars33** [Innovateninjas/Paws-frontend#297] opened 2024-05-12 09:21 UTC
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any page except home
2. Scroll down to bottom
3. there is an overflow issue along the X-axis 

kindly add me as a contributor to solve this issue.

**Comment by codewarnab** [comment] 2024-05-12 21:43
Assigned ! After your investigation share why is that issue occurring and in which page you need change code

**Comment by darkars33** [comment] 2024-05-13 17:57
the Make Your Mark! page this issue is faced due to extra padding along the x-axis.

**Comment by rishicds** [comment] 2024-05-16 19:02
@darkars33 thanks for the insight, if you have solved it feel free to open a pr

**Comment by Vaibhavsg17** [comment] 2024-06-05 20:06
@codewarnab if the issue is still unsolved you can assign it to me

**Comment by codewarnab** [comment] 2024-06-06 04:56
no it has been fixed or being worked on some pr

**Closed** 2024-06-06 04:56 UTC
Labels: level3, gssoc
